

spring:
    datasource:
        url: jdbc:mysql://121.41.91.101:3306/pokemondb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        database: 0
        host: 121.41.91.101
        port: 6379
        password:
        timeout: 0


mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.pkm.pkmdb.object


